name: CI
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.10"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v2
        with:
          files: lcov.info
      - name: Install system dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y \
            xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev \
            libxi-dev libxext-dev libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - name: Run tests
        run: >-
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' \
            julia --color=yes --project=. --threads=auto -e 'using Pkg; Pkg.test("DGGS", coverage=true)'
  docs:
    name: Documentation
    runs-on: self-hosted
    permissions:
      contents: write
      statuses: write
      actions: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: julia-actions/cache@v1
      - name: Install system dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y \
            xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev \
            libxi-dev libxext-dev libcairo2-dev libfreetype6-dev libffi-dev libjpeg-dev libpng-dev libz-dev
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install documentation dependencies
        run: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --project=docs -e 'using Pkg; Pkg.Registry.update(); pkg"dev ."; Pkg.instantiate(); Pkg.precompile(); Pkg.status()'
      - uses: julia-actions/julia-docdeploy@v1
        with:
          prefix: DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
